import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { FileText, Download, Eye, Calendar, Clock, User } from "lucide-react";
import { Link } from "react-router-dom";
import jsPDF from 'jspdf';

type ReportCardProps = {
  id: string;
  title: string;
  description: string;
  date: string;
  imageUrl?: string;
  userRole: "patient" | "doctor" | "admin";
  patientName?: string;
  patientAge?: number | null;
  patientGender?: string | null;
  patientFullName?: string;
};

export function ReportCard({
  id,
  title,
  description,
  date,
  imageUrl,
  userRole,
  patientName,
  patientAge,
  patientGender,
  patientFullName,
}: ReportCardProps) {
  const reportDate = new Date(date).toLocaleDateString();
  const reportTime = new Date(date).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

  const handleDownloadReport = () => {
    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.text('AI Analysis Report', 10, 10);

    doc.setFontSize(12);
    doc.text(`Report generated on ${reportDate} at ${reportTime}`, 10, 20);

    let yOffset = 30;
    if (patientFullName || patientGender) {
      doc.text(`Patient: ${patientFullName || 'N/A'} Gender: ${patientGender || 'N/A'}`, 10, yOffset);
      yOffset += 10;
    }

    doc.setFontSize(14);
    doc.text('Findings:', 10, yOffset + 10);
    doc.setFontSize(12);

    const splitDescription = doc.splitTextToSize(description, 180);
    doc.text(splitDescription, 10, yOffset + 20);

    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(10);
    doc.text(`Report ID: ${id}`, 10, pageHeight - 10);

    doc.save(`Report_${id}.pdf`);
  };

  return (
    <Card>
      <CardHeader className="pb-2">
        <div className="flex justify-between items-center">
          <CardTitle className="text-lg flex items-center gap-2">
            <FileText className="h-5 w-5 text-primary" />
            {title}
          </CardTitle>
          <span className="text-xs text-muted-foreground flex items-center gap-1">
             <Calendar className="h-3 w-3" /> {reportDate}
          </span>
        </div>
        {userRole === "patient" && (
           <div className="text-sm text-muted-foreground mt-1 space-y-1">
              <div className="flex items-center gap-4">
                 <span className="flex items-center gap-1">
                    Age: {patientAge ?? 'N/A'}
                 </span>
                 <span className="flex items-center gap-1">
                    Gender: {patientGender ?? 'N/A'}
                 </span>
                  <span className="flex items-center gap-1">
                    <Clock className="h-3 w-3" /> {reportTime}
                  </span>
              </div>
           </div>
        )}
        {userRole === "doctor" && patientName && (
          <CardDescription>Patient: {patientName}</CardDescription>
        )}
      </CardHeader>
      <CardContent>
        <p className="text-sm">{description}</p>
        <p className="text-xs text-muted-foreground italic mt-1">Report generated by AI analysis.</p>
      </CardContent>
      <CardFooter className="flex justify-between">
        {userRole !== "patient" && (
          <Button variant="outline" size="sm" asChild>
            <Link to={`/reports/${id}`}>
              <Eye className="mr-2 h-4 w-4" /> View
            </Link>
          </Button>
        )}
        <Button variant="secondary" size="sm" onClick={handleDownloadReport}>
          <Download className="mr-2 h-4 w-4" /> Download
        </Button>
      </CardFooter>
    </Card>
  );
}
